from __future__ import annotations

import chess

"""Action space definition for AlphaZero-style chess policy head.

This project uses the canonical fixed action head shape:
- board squares: 8 x 8 = 64 from-squares
- per-square move templates: 73 planes
- total policy dimension: 64 * 73 = 4672

Why fixed-size?
- Neural nets require a fixed output width.
- Legal moves vary by state, so we output a superset and then mask illegal actions.
"""

# AlphaZero chess convention: 8x8x73 = 4672
ACTION_PLANES = 73
ACTION_SIZE = 64 * ACTION_PLANES

# 8 sliding directions used by queen-like rays (also cover rook/bishop/king/pawn forward patterns).
SLIDING_DIRECTIONS = [
    (0, 1),    # N
    (0, -1),   # S
    (1, 0),    # E
    (-1, 0),   # W
    (1, 1),    # NE
    (-1, 1),   # NW
    (1, -1),   # SE
    (-1, -1),  # SW
]

# Knight jump templates.
KNIGHT_OFFSETS = [
    (1, 2),
    (2, 1),
    (2, -1),
    (1, -2),
    (-1, -2),
    (-2, -1),
    (-2, 1),
    (-1, 2),
]


def move_to_index(move: chess.Move) -> int:
    """Map a python-chess move to policy index in [0, 4671].

    Plane layout (73 planes per from-square):
    1) 0..55   : sliding rays (8 directions x 7 distances)
    2) 56..63  : knight jumps (8)
    3) 64..72  : underpromotions (N/B/R) x (left/forward/right)

    Notes:
    - Queen promotions are encoded via normal sliding planes.
    - Castling is encoded as king sliding (e1g1/e1c1/e8g8/e8c8).
    - En passant is encoded as normal pawn diagonal movement.

    Args:
        move: chess.Move generated by python-chess.

    Returns:
        int index in the flattened policy vector of length ACTION_SIZE.
        Returns 0 as safe fallback for impossible/unhandled templates.
    """
    from_sq = move.from_square
    to_sq = move.to_square

    ff = chess.square_file(from_sq)
    rf = chess.square_rank(from_sq)
    ft = chess.square_file(to_sq)
    rt = chess.square_rank(to_sq)

    df = ft - ff
    dr = rt - rf

    # 1) Knight templates.
    if (df, dr) in KNIGHT_OFFSETS:
        plane = 56 + KNIGHT_OFFSETS.index((df, dr))
        return from_sq * ACTION_PLANES + plane

    # 2) Underpromotion templates.
    if move.promotion in {chess.KNIGHT, chess.BISHOP, chess.ROOK}:
        promo_piece_to_block = {
            chess.KNIGHT: 0,
            chess.BISHOP: 1,
            chess.ROOK: 2,
        }
        block = promo_piece_to_block[move.promotion]

        # File direction for promotion move: -1 (left capture), 0 (forward), +1 (right capture)
        file_dir = -1 if df < 0 else (1 if df > 0 else 0)
        dir_idx = {-1: 0, 0: 1, 1: 2}[file_dir]
        plane = 64 + block * 3 + dir_idx
        return from_sq * ACTION_PLANES + plane

    # 3) Sliding templates (or queen promotions).
    step = max(abs(df), abs(dr))
    if step <= 0:
        return 0

    norm_df = 0 if df == 0 else (1 if df > 0 else -1)
    norm_dr = 0 if dr == 0 else (1 if dr > 0 else -1)

    if (norm_df, norm_dr) in SLIDING_DIRECTIONS and step <= 7:
        dir_idx = SLIDING_DIRECTIONS.index((norm_df, norm_dr))
        plane = dir_idx * 7 + (step - 1)
        return from_sq * ACTION_PLANES + plane

    return 0
