from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable

import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

from .alphazero_model import AlphaZeroNet
from .mcts import MCTS
from .selfplay import self_play_game


@dataclass
class TrainConfig:
    """Training hyperparameters.

    Core loop:
    for iter in iters:
      - run self-play games_per_iter (MCTS with current model)
      - collect (state, pi, z)
      - optimize model for epochs over collected data
      - save checkpoint
    """

    device: str = "cpu"
    games_per_iter: int = 4
    iters: int = 10
    sims: int = 64
    epochs: int = 2
    batch_size: int = 64
    lr: float = 1e-3
    out_dir: str = "checkpoints"
    # Save one checkpoint every N accumulated training epochs (iter * epochs).
    # Example: epochs=2 and checkpoint_every_epochs=10 -> save at iter 5,10,15...
    checkpoint_every_epochs: int = 10


class AlphaZeroTrainer:
    """Trainer for AlphaZero-style self-play + supervised update.

    Supervision targets are generated by search:
    - policy target pi from MCTS visit distribution
    - value target z from terminal game result

    Loss:
      L = CE(pi, softmax(logits)) + MSE(v, z)
    """

    def __init__(self, cfg: TrainConfig):
        self.cfg = cfg
        self.model = AlphaZeroNet().to(cfg.device)
        self.optim = torch.optim.Adam(self.model.parameters(), lr=cfg.lr)
        Path(cfg.out_dir).mkdir(parents=True, exist_ok=True)

    def _fit(self, states: np.ndarray, policies: np.ndarray, values: np.ndarray):
        """Run gradient updates on one aggregated self-play dataset.

        Inputs:
            states:   [N, 18, 8, 8]
            policies: [N, 4672]
            values:   [N]
        """
        ds = TensorDataset(
            torch.tensor(states, dtype=torch.float32),
            torch.tensor(policies, dtype=torch.float32),
            torch.tensor(values, dtype=torch.float32).unsqueeze(-1),
        )
        dl = DataLoader(ds, batch_size=self.cfg.batch_size, shuffle=True)

        self.model.train()
        for _ in range(self.cfg.epochs):
            for x, p_t, v_t in dl:
                x = x.to(self.cfg.device)
                p_t = p_t.to(self.cfg.device)
                v_t = v_t.to(self.cfg.device)

                logits, v = self.model(x)

                # Policy loss: cross-entropy with soft targets pi.
                logp = F.log_softmax(logits, dim=-1)
                policy_loss = -(p_t * logp).sum(dim=-1).mean()

                # Value loss: scalar regression to z in [-1, 1].
                value_loss = F.mse_loss(v, v_t)

                loss = policy_loss + value_loss

                self.optim.zero_grad()
                loss.backward()
                self.optim.step()

    def train_loop(self, on_log: Callable[[dict], None] | None = None):
        """Run complete iterative training loop and emit logs via callback."""
        for it in range(1, self.cfg.iters + 1):
            self.model.eval()
            mcts = MCTS(self.model, device=self.cfg.device, simulations=self.cfg.sims)

            samples = []
            results = {"1-0": 0, "0-1": 0, "1/2-1/2": 0, "*": 0}

            # 1) Self-play data generation.
            for g in range(self.cfg.games_per_iter):
                s, r = self_play_game(mcts)
                samples.extend(s)
                results[r] = results.get(r, 0) + 1
                if on_log:
                    on_log(
                        {
                            "event": "selfplay_game",
                            "iter": it,
                            "game": g + 1,
                            "result": r,
                            "samples": len(s),
                        }
                    )

            if not samples:
                if on_log:
                    on_log({"event": "iter_skipped", "iter": it, "reason": "no samples"})
                continue

            states = np.stack([x.state for x in samples], axis=0)
            policies = np.stack([x.policy for x in samples], axis=0)
            values = np.array([x.value for x in samples], dtype=np.float32)

            # 2) Gradient updates.
            self._fit(states, policies, values)

            # 3) Periodic checkpointing by accumulated epoch count.
            total_epochs_done = it * self.cfg.epochs
            should_save = (
                total_epochs_done % max(1, self.cfg.checkpoint_every_epochs) == 0
                or it == self.cfg.iters
            )

            ckpt_path = None
            if should_save:
                ckpt = Path(self.cfg.out_dir) / f"az_iter_{it:03d}.pt"
                torch.save({"model": self.model.state_dict(), "iter": it, "results": results}, ckpt)
                ckpt_path = str(ckpt)

            if on_log:
                on_log(
                    {
                        "event": "iter_done",
                        "iter": it,
                        "checkpoint": ckpt_path,
                        "results": results,
                        "dataset": len(samples),
                        "total_epochs_done": total_epochs_done,
                    }
                )
